title: "weupseanet's Blog"
description: "分享技术、OJ题解以及个人生活点滴"
author: "weupseanet"
email: "your-email@example.com"

theme: minima
url: "https://weupseanet.github.io"

social_links:
  - name: "GitHub"
    url: "https://github.com/weupseanet"
  - name: "Twitter"
    url: "https://twitter.com/weupseanet"

paginate: 5
paginate_path: "/page:num"
